# Generated by Django 2.0.6 on 2018-07-21 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_Holder_Name', models.CharField(default='John Smith', max_length=120)),
                ('number', models.CharField(default='1234123412341234', max_length=16)),
                ('expiration', models.CharField(default='MM/YY', max_length=5)),
                ('cvc', models.CharField(default='123', max_length=3)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_image_path)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('home_addr', models.CharField(blank=True, max_length=120)),
                ('nick_name', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('profile_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(default='Miami', max_length=64)),
                ('state', models.CharField(default='FL', max_length=2)),
                ('zip_code', models.CharField(default='33199', max_length=5)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
