# Generated by Django 2.0.6 on 2018-07-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rates',
            field=models.IntegerField(default=1),
        ),
    ]
