# Generated by Django 2.0.6 on 2018-07-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amountsold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
